@startuml
class Persona{
nombre : String
edad : int
mostrar()
}
class Empleado{
salarioBruto : float
}

class Directivo {
categoria : String
}

class Cliente {
telefono : String
}

class Empresa{

}

Persona <|-- Empleado
Persona <|-- Cliente
Empleado <|-- Directivo
Directivo "0..*" ----- "0..*"Empleado : Subordinado
@enduml